import type { ChangelogEntry } from "./types";

// AUTO-GENERATED by `pnpm changelog:gen` from `Changelog:` commit trailers.
// Do not edit by hand. CI (develop) fails if this file drifts from git history.
export const GENERATED: ChangelogEntry[] = [];
