import type { ChangelogEntry } from "./types";

// AUTO-GENERATED by `pnpm changelog:gen` from `Changelog:` commit trailers.
// Do not edit by hand. CI (develop) fails if this file drifts from git history.
export const GENERATED: ChangelogEntry[] = [
  {
    date: "2026-07-27",
    kind: "fixed",
    title: "The weekly digest sends, and covers the right week",
    description:
      "The health digest had never actually gone out, and would have reported every overdue item ever rather than the week it is headed with. It is now scoped to its own period, and a run that cannot send is reported instead of quietly counting as a success.",
  },
  {
    date: "2026-07-27",
    kind: "fixed",
    title: "Ask AI answers survive leaving the page",
    description:
      "Reloading or navigating away mid-answer used to lose the whole turn. The answer now finishes and is saved regardless, and it's waiting for you when you come back.",
  },
  {
    date: "2026-07-26",
    kind: "new",
    title: "Charts in your reports",
    description:
      "Report Builder gains a chart block — donut and bar charts shaped from your board data, configured in the builder rail, and rendered in both the live preview and the exported PDF.",
  },
  {
    date: "2026-07-26",
    kind: "new",
    title: "Ask AI can make the change for you",
    description:
      "Ask AI no longer stops at telling you what to do. It proposes the change as a confirm card in the thread, spelling out exactly what it will write — and nothing touches your board until you approve it. Cancel and it's dropped.",
  },
  {
    date: "2026-07-26",
    kind: "fixed",
    title: "Assignment notifications from connected agents",
    description:
      "Being assigned to an item by a connected AI client now notifies you, just as an in-app assignment does.",
  },
  {
    date: "2026-07-25",
    kind: "improved",
    title: "Settings, redesigned",
    description:
      "Settings is now its own area with proper navigation instead of one long page — separate Account, Organization and AI sections. Rename your organization, leave one, manage appearance and security, and copy your server URL straight from a step-by-step guide for connecting Claude.",
  },
  {
    date: "2026-07-25",
    kind: "new",
    title: "Delete your own account",
    description:
      "The Account danger zone now lets you permanently delete your account, confirming by typing your email. If you're the sole owner of an organization you'll be asked to hand it over first, so no workspace is left stranded.",
  },
  {
    date: "2026-07-25",
    kind: "improved",
    title: "Sign in and land where you were going",
    description:
      "Opening a link while signed out now takes you to that page once you've signed in, instead of dropping you on your dashboard.",
  },
  {
    date: "2026-07-24",
    kind: "new",
    title: "Connect Claude to your workspace",
    description:
      "Add Monolith as a connector in Claude Desktop or claude.ai and let it work with your boards — list them, search and read items, and create or update them. It connects as you and sees exactly what you can see, nothing more. Approve it once from a consent screen, and revoke it any time from Settings.",
  },
  {
    date: "2026-07-20",
    kind: "new",
    title: "Let AI decide inside an automation",
    description:
      "Add an AI step to any automation rule: write the instruction in plain language, then tick exactly which actions the AI is allowed to take — set a status, set percent, move to a group, or notify someone. Dry-run it to preview the decision before you turn the rule on.",
  },
  {
    date: "2026-07-20",
    kind: "new",
    title: "Autopilot, a scheduled agent for your board",
    description:
      "Switch on Autopilot and your board gets tended on a cadence, with only the housekeeping you tick: triage new items into the group that fits, chase overdue owners, and keep goal rollups current. It works under its own bot identity, so every change it makes is attributable.",
  },
  {
    date: "2026-07-20",
    kind: "new",
    title: "Find similar items",
    description:
      'Any item now surfaces others across your boards that are about the same thing, even when they share no words — "onboarding" turns up "New-hire checklist".',
  },
  {
    date: "2026-07-20",
    kind: "improved",
    title: "Ask AI searches by meaning",
    description:
      "Ask AI can look up items by what they're about rather than the exact words in their names.",
  },
  {
    date: "2026-07-17",
    kind: "improved",
    title: "Zoom out on the Timeline",
    description:
      "The Timeline adds quarter and year zoom levels alongside day, week and month, fills the full width of the canvas, and no longer wraps its header dates.",
  },
  {
    date: "2026-07-17",
    kind: "improved",
    title: "Sub-items nest on the Timeline",
    description:
      "Sub-items now sit under their parent and start collapsed, so a busy board opens as a compact overview you expand row by row — including parents that have no dates of their own but scheduled sub-items underneath.",
  },
  {
    date: "2026-07-17",
    kind: "new",
    title: "Chart items by when they were created",
    description:
      "Timeline bars can now be driven by an item's Created at or Updated at timestamp, not just date columns.",
  },
  {
    date: "2026-07-17",
    kind: "improved",
    title: "Timestamps no longer flash blank",
    description:
      "Dates and times appear on first paint instead of filling in a moment later.",
  },
  {
    date: "2026-07-17",
    kind: "fixed",
    title: "Report covers show your workspace name",
    description:
      "The report cover printed an internal ID instead of your workspace's name, in both the live preview and the exported PDF.",
  },
  {
    date: "2026-07-17",
    kind: "fixed",
    title: "AI report summaries respect permissions",
    description:
      "Only owners and editors can generate an AI summary for a report — viewers could previously trigger one they had no way to save.",
  },
  {
    date: "2026-07-27",
    kind: "fixed",
    title: 'Autopilot now posts as "Monolith Autopilot"',
    description:
      "The scheduled board agent still signed its updates with the old product name.",
  },
  {
    date: "2026-07-27",
    kind: "new",
    title: "Read a whole board over MCP in one call",
    description:
      "Connected AI clients can now list a board's items and their values in a single request, instead of fetching items one at a time — and a truncated search now says so.",
  },
  {
    date: "2026-07-27",
    kind: "fixed",
    title: 'Consent screen and MCP setup say "Monolith"',
    description:
      "The OAuth approval screen and the Connect-via-MCP guide referred to the product by its old name.",
  },
  {
    date: "2026-07-27",
    kind: "improved",
    title: "Ask AI shows what it is doing",
    description:
      'Ask AI now shows a live "Thinking..." indicator the moment you hit send, tells you when it starts reading your boards, and holds the composer until the answer lands so a slow question can no longer look like a broken one.',
  },
  {
    date: "2026-07-17",
    kind: "new",
    title: "Board reports",
    description:
      "Build a shareable report from any board — choose the sections you want, preview it live, and add an AI-written summary or write your own.",
  },
  {
    date: "2026-07-17",
    kind: "improved",
    title: "Ask AI gets its own page",
    description:
      "Ask AI moved out of the popup into a full page, with saved conversations you can return to and answers that stream in as they're written.",
  },
  {
    date: "2026-07-17",
    kind: "improved",
    title: "Faster, smoother everywhere",
    description:
      "Boards, your home, dashboards, and the calendar and timeline views all load quicker and respond more fluidly.",
  },
  {
    date: "2026-07-10",
    kind: "improved",
    title: "A refreshed look for Monolith",
    description:
      "A cleaner, dark-first redesign across boards and tables — new type, calmer color, and sharper detail throughout.",
  },
  {
    date: "2026-07-05",
    kind: "new",
    title: "Bulk actions in Table view",
    description:
      "Select multiple rows and move, set status, assign people, or delete them all at once. Shift-click to select a range; select-all respects your active filter.",
  },
  {
    date: "2026-07-05",
    kind: "new",
    title: "Everything assigned to you, in one place",
    description:
      "The new My Work page gathers every item assigned to you across all your boards, grouped by when it's due — Overdue, Today, This week, and Later.",
  },
  {
    date: "2026-07-05",
    kind: "new",
    title: "Search across all your items",
    description:
      "Open the command palette and search items by name across every board, then jump straight to one.",
  },
  {
    date: "2026-07-05",
    kind: "new",
    title: "Filter, sort and search any board",
    description:
      "A board toolbar to filter by column, sort, and quick-search — narrowing what you see instantly, without reloading.",
  },
  {
    date: "2026-07-05",
    kind: "improved",
    title: "A guided start for new workspaces",
    description:
      "New users now land on a friendly home that walks them to their first board instead of a dead end.",
  },
  {
    date: "2026-07-05",
    kind: "improved",
    title: "Nav that works on mobile",
    description:
      "Navigation collapses into a slide-in drawer on phones and small screens.",
  },
  {
    date: "2026-07-05",
    kind: "improved",
    title: "Edit your display name",
    description:
      "Change the name that shows on your profile and across the workspace from Settings.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Currency columns",
    description:
      "Track money on your boards with a new currency column — pick from 44 currencies, switch a column's currency in one click, and see totals in the footer and on collapsed parents.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Completion widgets for dashboards",
    description:
      "See how complete any board is at a glance — an overall percentage plus a progress bar per group, measured by percent or by done statuses.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Quick-edit from Calendar and Timeline",
    description:
      "Click a calendar event or timeline bar to update its status or progress on the spot, without opening the full item.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Keep status and progress in sync",
    description:
      'Automations gain a "percent reached" trigger and a "set percent" action, with ready-made recipes: mark items Done at 100%, or jump to 100% when marked Done.',
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Reorder columns",
    description:
      "Drag a column header — or use Move left / Move right in its menu — to rearrange your table. Works on touch too.",
  },
  {
    date: "2026-07-03",
    kind: "improved",
    title: "Overdue dates stand out",
    description:
      "Date cells turn red when an item is past due and not yet done.",
  },
  {
    date: "2026-07-03",
    kind: "improved",
    title: "Polished Excel exports",
    description:
      "Exported spreadsheets now open formatted: real number and percent cells, progress data bars, currency formats, group colors, and a frozen, filterable header.",
  },
  {
    date: "2026-07-02",
    kind: "improved",
    title: "Smoother loading",
    description:
      "Boards, dashboards, and workload pages now load with content-shaped placeholders instead of blank screens, and feel snappier throughout.",
  },
  {
    date: "2026-07-02",
    kind: "improved",
    title: "Errors no longer fail silently",
    description:
      "When a change can't be saved you get a clear error message, and broken links land on friendly error pages instead of a crash.",
  },
  {
    date: "2026-06-29",
    kind: "improved",
    title: "Calendar touch targets",
    description:
      "Calendar navigation buttons are comfortably tappable on iPad.",
  },
  {
    date: "2026-06-29",
    kind: "improved",
    title: "Calendar drag on touch",
    description:
      "Long-press an event to drag it to another day on iPad; a quick swipe scrolls.",
  },
  {
    date: "2026-06-29",
    kind: "improved",
    title: "Kanban touch targets",
    description: "Group-by and add-card controls are now finger-sized on iPad",
  },
  {
    date: "2026-06-26",
    kind: "new",
    title: "Import and export boards as spreadsheets",
    description:
      "Export any board to an Excel spreadsheet, or bulk-create items by importing one.",
  },
  {
    date: "2026-06-26",
    kind: "improved",
    title: "Snappier board interactions",
    description:
      "Resizing columns, dragging items, and live presence updates now feel smoother and more responsive.",
  },
  {
    date: "2026-06-26",
    kind: "new",
    title: "See who created each item",
    description:
      "Every item and subitem now shows who created it and when, in two read-only columns at the end of the board (and in the item panel) — a permanent record that can't be edited.",
  },
  {
    date: "2026-06-24",
    kind: "new",
    title: "Generate dashboards with AI",
    description:
      "Let AI design a dashboard for any board — pick a board, approve a privacy-safe summary (no cell data leaves your workspace), and get a ready-made set of charts and metrics to keep, discard, or regenerate.",
  },
];
