import type { ChangelogEntry } from "./types";

// AUTO-GENERATED by `pnpm changelog:gen` from `Changelog:` commit trailers.
// Do not edit by hand. CI (develop) fails if this file drifts from git history.
export const GENERATED: ChangelogEntry[] = [
  {
    date: "2026-07-05",
    kind: "new",
    title: "Bulk actions in Table view",
    description:
      "Select multiple rows and move, set status, assign people, or delete them all at once. Shift-click to select a range; select-all respects your active filter.",
  },
  {
    date: "2026-07-05",
    kind: "new",
    title: "Everything assigned to you, in one place",
    description:
      "The new My Work page gathers every item assigned to you across all your boards, grouped by when it's due — Overdue, Today, This week, and Later.",
  },
  {
    date: "2026-07-05",
    kind: "new",
    title: "Search across all your items",
    description:
      "Open the command palette and search items by name across every board, then jump straight to one.",
  },
  {
    date: "2026-07-05",
    kind: "new",
    title: "Filter, sort and search any board",
    description:
      "A board toolbar to filter by column, sort, and quick-search — narrowing what you see instantly, without reloading.",
  },
  {
    date: "2026-07-05",
    kind: "improved",
    title: "A guided start for new workspaces",
    description:
      "New users now land on a friendly home that walks them to their first board instead of a dead end.",
  },
  {
    date: "2026-07-05",
    kind: "improved",
    title: "Nav that works on mobile",
    description:
      "Navigation collapses into a slide-in drawer on phones and small screens.",
  },
  {
    date: "2026-07-05",
    kind: "improved",
    title: "Edit your display name",
    description:
      "Change the name that shows on your profile and across the workspace from Settings.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Currency columns",
    description:
      "Track money on your boards with a new currency column — pick from 44 currencies, switch a column's currency in one click, and see totals in the footer and on collapsed parents.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Completion widgets for dashboards",
    description:
      "See how complete any board is at a glance — an overall percentage plus a progress bar per group, measured by percent or by done statuses.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Quick-edit from Calendar and Timeline",
    description:
      "Click a calendar event or timeline bar to update its status or progress on the spot, without opening the full item.",
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Keep status and progress in sync",
    description:
      'Automations gain a "percent reached" trigger and a "set percent" action, with ready-made recipes: mark items Done at 100%, or jump to 100% when marked Done.',
  },
  {
    date: "2026-07-03",
    kind: "new",
    title: "Reorder columns",
    description:
      "Drag a column header — or use Move left / Move right in its menu — to rearrange your table. Works on touch too.",
  },
  {
    date: "2026-07-03",
    kind: "improved",
    title: "Overdue dates stand out",
    description:
      "Date cells turn red when an item is past due and not yet done.",
  },
  {
    date: "2026-07-03",
    kind: "improved",
    title: "Polished Excel exports",
    description:
      "Exported spreadsheets now open formatted: real number and percent cells, progress data bars, currency formats, group colors, and a frozen, filterable header.",
  },
  {
    date: "2026-07-02",
    kind: "improved",
    title: "Smoother loading",
    description:
      "Boards, dashboards, and workload pages now load with content-shaped placeholders instead of blank screens, and feel snappier throughout.",
  },
  {
    date: "2026-07-02",
    kind: "improved",
    title: "Errors no longer fail silently",
    description:
      "When a change can't be saved you get a clear error message, and broken links land on friendly error pages instead of a crash.",
  },
  {
    date: "2026-06-29",
    kind: "improved",
    title: "Calendar touch targets",
    description:
      "Calendar navigation buttons are comfortably tappable on iPad.",
  },
  {
    date: "2026-06-29",
    kind: "improved",
    title: "Calendar drag on touch",
    description:
      "Long-press an event to drag it to another day on iPad; a quick swipe scrolls.",
  },
  {
    date: "2026-06-29",
    kind: "improved",
    title: "Kanban touch targets",
    description: "Group-by and add-card controls are now finger-sized on iPad",
  },
  {
    date: "2026-06-26",
    kind: "new",
    title: "Import and export boards as spreadsheets",
    description:
      "Export any board to an Excel spreadsheet, or bulk-create items by importing one.",
  },
  {
    date: "2026-06-26",
    kind: "improved",
    title: "Snappier board interactions",
    description:
      "Resizing columns, dragging items, and live presence updates now feel smoother and more responsive.",
  },
  {
    date: "2026-06-26",
    kind: "new",
    title: "See who created each item",
    description:
      "Every item and subitem now shows who created it and when, in two read-only columns at the end of the board (and in the item panel) — a permanent record that can't be edited.",
  },
  {
    date: "2026-06-24",
    kind: "new",
    title: "Generate dashboards with AI",
    description:
      "Let AI design a dashboard for any board — pick a board, approve a privacy-safe summary (no cell data leaves your workspace), and get a ready-made set of charts and metrics to keep, discard, or regenerate.",
  },
];
