import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  parseChangelogTrailers,
  RECORD_SEP,
  FIELD_SEP,
  VALUE_SEP,
} from "../src/lib/changelog/parse";

// Translate a separator char into a git pretty-format `%xNN` hex escape.
const hex = (c: string) => `%x${c.charCodeAt(0).toString(16).padStart(2, "0")}`;

// Per commit: short author date, FIELD_SEP, the Changelog trailer values
// (VALUE_SEP between multiple), then RECORD_SEP.
const format =
  `%ad${hex(FIELD_SEP)}` +
  `%(trailers:key=Changelog,valueonly,separator=${hex(VALUE_SEP)})` +
  `${hex(RECORD_SEP)}`;

const gitLog = execFileSync(
  "git",
  ["log", "--date=short", `--format=${format}`],
  { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
);

const entries = parseChangelogTrailers(gitLog);

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "../src/lib/changelog/generated.ts");

const file = `import type { ChangelogEntry } from "./types";

// AUTO-GENERATED by \`pnpm changelog:gen\` from \`Changelog:\` commit trailers.
// Do not edit by hand. CI (develop) fails if this file drifts from git history.
export const GENERATED: ChangelogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(outPath, file);
console.log(
  `changelog: wrote ${entries.length} generated entr${
    entries.length === 1 ? "y" : "ies"
  }`,
);
